export const PATHS = [
  {
    id: "brave",
    name: "MUTIG",
    floors: 5,
    mins: "4–6 Min",
    blurb: "Kurzer Ansturm. Perfekt zum Warmwerden.",
    color: "#3ecf5a",
    unlock: 0,
    difficulty: 1,
  },
  {
    id: "heroic",
    name: "HELDENHAFT",
    floors: 10,
    mins: "10–14 Min",
    blurb: "Dichter, härter, mehr Eliten.",
    color: "#3aa0ff",
    unlock: 1,
    difficulty: 1.45,
  },
  {
    id: "legend",
    name: "LEGENDÄR",
    floors: 15,
    mins: "18–24 Min",
    blurb: "Langer Aufstieg. Nur für eingespielte Trupps.",
    color: "#c45cff",
    unlock: 2,
    difficulty: 1.9,
  },
];

export const HEROES = [
  {
    id: "berserker",
    name: "Ragnar",
    title: "Berserker",
    role: "Nahkampf · Durchbruch",
    blurb: "Bricht Linien mit Äxten. Leichte Hiebe laden den Donnerschlag.",
    color: "#e8a020",
    accent: "#7a3a10",
    skin: "#f0c090",
    hair: "#f2d24a",
    range: 2.15,
    speed: 6.4,
    hp: 220,
    light: { dmg: 18, cd: 0.28, combo: 3 },
    heavy: { dmg: 52, charge: 0.7 },
    skill: { dmg: 64, cd: 8, name: "Wutsturm" },
    kit: {
      light: "Axtkombination, lädt Schwer",
      heavy: "Donnerschlag · Perfekt: Schockwelle",
      skill: "Wutsturm — Slam + Tempo",
    },
    icon: "🪓",
    style: "melee",
  },
  {
    id: "ranger",
    name: "Lyra",
    title: "Waldläuferin",
    role: "Fernkampf · Kontrolle",
    blurb: "Hält Distanz. Perfekte Schwere spaltet den Schuss.",
    color: "#d94f8c",
    accent: "#3a6b2a",
    skin: "#f3c4a0",
    hair: "#6b2a18",
    range: 9.5,
    speed: 6.1,
    hp: 150,
    light: { dmg: 14, cd: 0.32, combo: 3 },
    heavy: { dmg: 44, charge: 0.75 },
    skill: { dmg: 18, cd: 9, name: "Pfeilhagel" },
    kit: {
      light: "Gezielte Pfeile",
      heavy: "Durchschuss · Perfekt: Split",
      skill: "Pfeilhagel — Fächer / Homing-Perk",
    },
    icon: "🏹",
    style: "ranged",
  },
  {
    id: "aegis",
    name: "Astrid",
    title: "Schildmaid",
    role: "Hybrid · Fläche",
    blurb: "Dreht sich durch Horden. Werfende Axt betäubt auf Perfekt.",
    color: "#7ec8e8",
    accent: "#c9d6de",
    skin: "#f0c090",
    hair: "#f4f0e8",
    range: 2.4,
    speed: 6.2,
    hp: 200,
    light: { dmg: 16, cd: 0.26, combo: 4 },
    heavy: { dmg: 48, charge: 0.72 },
    skill: { dmg: 12, cd: 8.5, name: "Wirbelklinge" },
    kit: {
      light: "Kreiselnde Klingen",
      heavy: "Axtwurf · Perfekt: Betäubung",
      skill: "Wirbelklinge — Spin-Dash",
    },
    icon: "🛡️",
    style: "melee",
  },
  {
    id: "pyre",
    name: "Ember",
    title: "Rakete",
    role: "Fernkampf · Explosion",
    blurb: "Feuerwerk auf Distanz. Cluster bei perfektem Schwerangriff.",
    color: "#e84a2a",
    accent: "#2a2a32",
    skin: "#e8b898",
    hair: "#f26a20",
    range: 8.2,
    speed: 6.0,
    hp: 155,
    light: { dmg: 13, cd: 0.34, combo: 3 },
    heavy: { dmg: 50, charge: 0.8 },
    skill: { dmg: 22, cd: 10, name: "Feuerwerk" },
    kit: {
      light: "Raketen",
      heavy: "Granate · Perfekt: Cluster",
      skill: "Feuerwerk — Barrage",
    },
    icon: "🎇",
    style: "ranged",
  },
  {
    id: "blast",
    name: "Nox",
    title: "Sprenger",
    role: "Fläche · Falle",
    blurb: "Wirft Bomben in Haufen. Perfekt vergrößert den Krater.",
    color: "#5a4a78",
    accent: "#1a1a22",
    skin: "#d8b090",
    hair: "#2a2430",
    range: 6.4,
    speed: 5.7,
    hp: 170,
    light: { dmg: 16, cd: 0.42, combo: 2 },
    heavy: { dmg: 60, charge: 0.85 },
    skill: { dmg: 28, cd: 11, name: "Teppich" },
    kit: {
      light: "Wurfbomben",
      heavy: "Große Bombe · Perfekt: Radius+",
      skill: "Teppichbomben",
    },
    icon: "💣",
    style: "ranged",
  },
  {
    id: "knave",
    name: "Grub",
    title: "Schurke",
    role: "Assassine · Tempo",
    blurb: "Flitzt durch Lücken. Perfekter Sprung reißt eine Blutung.",
    color: "#5aaa3a",
    accent: "#3a2810",
    skin: "#6cb84a",
    hair: "#2a1a08",
    range: 1.85,
    speed: 7.2,
    hp: 145,
    light: { dmg: 12, cd: 0.18, combo: 5 },
    heavy: { dmg: 40, charge: 0.6 },
    skill: { dmg: 30, cd: 7, name: "Raserei" },
    kit: {
      light: "Rasante Stiche",
      heavy: "Sprunghieb · Perfekt: Blutung",
      skill: "Raserei — Dash-Kette",
    },
    icon: "🗡️",
    style: "melee",
  },
];

export const PERKS = [
  { id: "light+", name: "Scharfe Klinge", desc: "+22% Leichtschaden", apply: (p) => (p.lightMul *= 1.22) },
  { id: "heavy+", name: "Brecher", desc: "+30% Schwer-Schaden", apply: (p) => (p.heavyMul *= 1.3) },
  { id: "skillcd", name: "Flinker Geist", desc: "Skill-CD −25%", apply: (p) => (p.skillCdMul *= 0.75) },
  { id: "hp", name: "Eiserne Haut", desc: "+25% max. LP und Heilung", apply: (p) => { p.maxHp *= 1.25; p.hp = Math.min(p.maxHp, p.hp + p.maxHp * 0.35); } },
  { id: "speed", name: "Sturmtritt", desc: "+16% Tempo", apply: (p) => (p.speedMul *= 1.16) },
  { id: "vamp", name: "Blutdurst", desc: "8% Lebensraub", apply: (p) => (p.vamp += 0.08) },
  { id: "charge", name: "Kampfrhythmus", desc: "Leicht füllt Schwer schneller", apply: (p) => (p.chargeGain *= 1.4) },
  { id: "crit", name: "Adlerauge", desc: "18% Krit (x2)", apply: (p) => (p.crit += 0.18) },
  { id: "armor", name: "Turmwächter", desc: "−18% erlittener Schaden", apply: (p) => (p.armor *= 0.82) },
  { id: "aoe", name: "Nachbeben", desc: "Leicht trifft im kleinen Kreis", apply: (p) => (p.aoe = true) },
  { id: "homing", name: "Sucher", desc: "Projektile lenken nach", apply: (p) => (p.homing = true) },
  { id: "multi", name: "Splittschuss", desc: "+1 Projektil", apply: (p) => (p.extraShots += 1) },
];

export const ENEMY_KINDS = {
  grunt: { name: "Kobold", hp: 55, dmg: 8, speed: 3.4, range: 1.6, color: "#5aaa3a", xp: 8, radius: 0.55 },
  archer: { name: "Schütze", hp: 40, dmg: 10, speed: 2.6, range: 7.2, color: "#c45a3a", xp: 10, radius: 0.5, ranged: true },
  knight: { name: "Wächter", hp: 120, dmg: 16, speed: 2.3, range: 1.9, color: "#8a90a8", xp: 16, radius: 0.7 },
  runner: { name: "Renner", hp: 36, dmg: 9, speed: 5.4, range: 1.4, color: "#c48a3a", xp: 9, radius: 0.48 },
  elite: { name: "Golem", hp: 420, dmg: 22, speed: 1.9, range: 2.4, color: "#6a8a4a", xp: 60, radius: 1.15, elite: true },
  boss: { name: "Turmwächter", hp: 900, dmg: 26, speed: 2.1, range: 2.8, color: "#8a3a3a", xp: 140, radius: 1.45, elite: true, boss: true },
};

export function floorPlan(pathId, index, total) {
  if (index === total - 1) return "boss";
  if (index === Math.floor(total / 2)) return "elite";
  if (index === total - 2 && total > 4) return "survival";
  const cycle = ["combat", "combat", "elite", "combat", "survival"];
  return cycle[index % cycle.length];
}

export function objectiveText(type) {
  if (type === "combat") return "Besiege alle Wellen";
  if (type === "elite") return "Bezwinge die Elite";
  if (type === "survival") return "Überlebe den Ansturm";
  return "Besiege den Wächter";
}
